region: ap-northeast-1
cluster: ecspresso-example
service: web
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 5m
plugins:
  - name: tfstate
    config:
      path: ../terraform/.terraform/terraform.tfstate
