region: ap-northeast-1
cluster: ecspresso-example
service: next
service_definition: ecspresso/secrets/ecs-service-def.json
task_definition: ecspresso/secrets/ecs-task-def.json
# service_definition: ecspresso/ecs-service-def.json
# task_definition: ecspresso/ecs-task-def.json
timeout: 5m
